version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL
  build:
    commands:
      - echo Building Docker image...
      - docker build -t dev-app .
      - docker tag dev-app:latest $ECR_URL/secure-python-app:latest
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $ECR_URL/secure-python-app:latest
